### ISSUE TITLE
[iOS] Cannot build with React Native 0.66 with Hermes

### ISSUE THREAD

**Issue by yruan** [sentiance/react-native-sentiance#159]
I created a demo project by using the latest React Native (0.66), and `hermes` is enabled in `./ios/Podfile`, `use_flipper!()` is commented out. (https://github.com/yruan/sentiance-demo)

The project can be built successfully without adding ```react-native-sentiance```.

After installing `react-native-sentiance` with `cocoaPods`, running `$ yarn ios` will fail with the following errors:

```
Undefined symbols for architecture x86_64:
  "_jump_fcontext", referenced from:
      folly::fibers::FiberImpl::deactivate() in libRCT-Folly.a(Fiber.o)
      folly::fibers::FiberImpl::activate() in libRCT-Folly.a(SimpleLoopController.o)
  "_make_fcontext", referenced from:
      folly::fibers::FiberImpl::FiberImpl(folly::Function<void ()>, unsigned char*, unsigned long) in libRCT-Folly.a(Fiber.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Same errors when running in Xcode IDE.

Hardware: Macbook Pro 2019 with Intel chip
macOS: Big Sur 11.6
Xcode: 13.0
Simulator: iPhone 13 with iOS 15
Cocoapods: 1.11.2
Yarn: 1.22.15
Node: 16.10.0
NPM: 7.24.0

**Comment by netomi** [comment]
This problem is caused by the '-all_load' linker flag that is specified in the podspec of the SENTSDK pod which is used as a dependency for by the react native bindings. This is unnecessary nowadays and we removed it in the latest release 5.11.2. If you update your pods to use this version the problem should be solved and you should be able to build with hermes activated.
